name: Formatting

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Dependencies
        run: pnpm install

      - name: Check linting
        run: pnpm lint
